### ISSUE TITLE
dfu-convert.py origin

### ISSUE THREAD

**Issue by tormodvolden** [plietar/dfuse-tool#5]
Hi,
I have a question about your dfu-convert.py, for the sake of attribution. Your dfu-convert.py has support for intel hex files, which was not in Antonio's original version (which we, with Antonio's blessing, host in our dfu-util.sf.net project). Did you add this yourself?

I am considering merging this functionality back into ours, and I would prefer to attribute the change to its original author.

Thanks in advance!
Tormod

**Comment by plietar** [comment]
To be honest it's been a really long time since I've written and used code in this repo.
I do vaguely remember adding the Intel hex support to it.

**Comment by tormodvolden** [comment]
Thanks. Intel HEX support (and additionally support for multiple segments) has now been added to our version at dfu-util.sourceforge.net
